//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTTTA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.LopHocs = new HashSet<LopHoc>();
        }
    
        public int MaGV { get; set; }
        public string TenGV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public int ThamNien { get; set; }
        public string HocVi { get; set; }
        public int Luong { get; set; }
        public string Mail { get; set; }
    
        public virtual DangNhap DangNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHocs { get; set; }
        public override string ToString()
        {
            return string.Format("GV{0} - {1} - Học vị {2} - Thâm niên {3} năm", MaGV.ToString(), TenGV, HocVi, ThamNien.ToString());
        }
    }
}
