//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTTTA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoaHoc()
        {
            this.LopHocs = new HashSet<LopHoc>();
        }
    
        public int MaKH { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public int SoTuanHoc { get; set; }
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHocs { get; set; }
        public override string ToString()
        {
            return string.Format("KH{0} - {1} - {2} Tuần - {3}", MaKH.ToString(), NgayBatDau.ToString(), SoTuanHoc.ToString(), TinhTrang);
        }
    }
}
