//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTTTA
{
    using QLTTTA.BUS;
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.BienLaiHocPhis = new HashSet<BienLaiHocPhi>();
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public int MaLH { get; set; }
        public int KhoaHoc { get; set; }
        public Nullable<int> MonHoc { get; set; }
        public Nullable<int> GiangVien { get; set; }
        public string CaHoc { get; set; }
        public string NgayHoc { get; set; }
        public string SoLuongHV { get; set; }
        public int SoTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienLaiHocPhi> BienLaiHocPhis { get; set; }
        public virtual GiangVien GiangVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
        public virtual KhoaHoc KhoaHoc1 { get; set; }
        public virtual MonHoc MonHoc1 { get; set; }
        public override string ToString()
        {
            return string.Format("LH{0} - Môn học: {1} - Ca: {2} - Ngày học: {3} - Số lượng HV: {4} - Số tiền: {5} VNĐ", MaLH.ToString(), MonHocBUS.Instance.getMonHoc((int)MonHoc).TenMH, CaHoc, NgayHoc, SoLuongHV, SoTien.ToString());
        }
    }
}
