//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTTTA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string CMND { get; set; }
        public int Luong { get; set; }
        public string Mail { get; set; }
    
        public virtual DangNhap DangNhap { get; set; }
    }
}
