//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTTTA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TTTA_DBEntities : DbContext
    {
        public TTTA_DBEntities()
            : base("name=TTTA_DBEntities")
        {
            this.Configuration.AutoDetectChangesEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BienLaiHocPhi> BienLaiHocPhis { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HocVien> HocViens { get; set; }
        public virtual DbSet<KetQua> KetQuas { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }
        public virtual DbSet<LopHoc> LopHocs { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
    
        public virtual int CapNhatDangNhap(string mail, string matKhau, string quyenDangNhap)
        {
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var quyenDangNhapParameter = quyenDangNhap != null ?
                new ObjectParameter("QuyenDangNhap", quyenDangNhap) :
                new ObjectParameter("QuyenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatDangNhap", mailParameter, matKhauParameter, quyenDangNhapParameter);
        }
    
        public virtual int CapNhatGiangVien(Nullable<int> maGV, string tenGV, Nullable<System.DateTime> ngaySinh, Nullable<int> thamNien, string hocVi, Nullable<int> luong, string mail)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var thamNienParameter = thamNien.HasValue ?
                new ObjectParameter("ThamNien", thamNien) :
                new ObjectParameter("ThamNien", typeof(int));
    
            var hocViParameter = hocVi != null ?
                new ObjectParameter("HocVi", hocVi) :
                new ObjectParameter("HocVi", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatGiangVien", maGVParameter, tenGVParameter, ngaySinhParameter, thamNienParameter, hocViParameter, luongParameter, mailParameter);
        }
    
        public virtual int CapNhatHocVien(Nullable<int> maHV, string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, string soDienThoai)
        {
            var maHVParameter = maHV.HasValue ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatHocVien", maHVParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, soDienThoaiParameter);
        }
    
        public virtual int CapNhatKetQua(Nullable<int> maHocVien, Nullable<int> maLopHoc, Nullable<int> maKhoaHoc, Nullable<double> diemGiuaKy, Nullable<double> diemCuoiKy, Nullable<double> diemTB)
        {
            var maHocVienParameter = maHocVien.HasValue ?
                new ObjectParameter("MaHocVien", maHocVien) :
                new ObjectParameter("MaHocVien", typeof(int));
    
            var maLopHocParameter = maLopHoc.HasValue ?
                new ObjectParameter("MaLopHoc", maLopHoc) :
                new ObjectParameter("MaLopHoc", typeof(int));
    
            var maKhoaHocParameter = maKhoaHoc.HasValue ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(int));
    
            var diemGiuaKyParameter = diemGiuaKy.HasValue ?
                new ObjectParameter("DiemGiuaKy", diemGiuaKy) :
                new ObjectParameter("DiemGiuaKy", typeof(double));
    
            var diemCuoiKyParameter = diemCuoiKy.HasValue ?
                new ObjectParameter("DiemCuoiKy", diemCuoiKy) :
                new ObjectParameter("DiemCuoiKy", typeof(double));
    
            var diemTBParameter = diemTB.HasValue ?
                new ObjectParameter("DiemTB", diemTB) :
                new ObjectParameter("DiemTB", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatKetQua", maHocVienParameter, maLopHocParameter, maKhoaHocParameter, diemGiuaKyParameter, diemCuoiKyParameter, diemTBParameter);
        }
    
        public virtual int CapNhatKhoaHoc(Nullable<int> maKH, Nullable<System.DateTime> ngayBatDau, Nullable<int> soTuanHoc, string tinhTrang)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var soTuanHocParameter = soTuanHoc.HasValue ?
                new ObjectParameter("SoTuanHoc", soTuanHoc) :
                new ObjectParameter("SoTuanHoc", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatKhoaHoc", maKHParameter, ngayBatDauParameter, soTuanHocParameter, tinhTrangParameter);
        }
    
        public virtual int CapNhatLopHoc(Nullable<int> maLH, Nullable<int> khoaHoc, Nullable<int> monHoc, Nullable<int> giangVien, string caHoc, string ngayHoc, string soLuongHV, Nullable<int> soTien)
        {
            var maLHParameter = maLH.HasValue ?
                new ObjectParameter("MaLH", maLH) :
                new ObjectParameter("MaLH", typeof(int));
    
            var khoaHocParameter = khoaHoc.HasValue ?
                new ObjectParameter("KhoaHoc", khoaHoc) :
                new ObjectParameter("KhoaHoc", typeof(int));
    
            var monHocParameter = monHoc.HasValue ?
                new ObjectParameter("MonHoc", monHoc) :
                new ObjectParameter("MonHoc", typeof(int));
    
            var giangVienParameter = giangVien.HasValue ?
                new ObjectParameter("GiangVien", giangVien) :
                new ObjectParameter("GiangVien", typeof(int));
    
            var caHocParameter = caHoc != null ?
                new ObjectParameter("CaHoc", caHoc) :
                new ObjectParameter("CaHoc", typeof(string));
    
            var ngayHocParameter = ngayHoc != null ?
                new ObjectParameter("NgayHoc", ngayHoc) :
                new ObjectParameter("NgayHoc", typeof(string));
    
            var soLuongHVParameter = soLuongHV != null ?
                new ObjectParameter("SoLuongHV", soLuongHV) :
                new ObjectParameter("SoLuongHV", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatLopHoc", maLHParameter, khoaHocParameter, monHocParameter, giangVienParameter, caHocParameter, ngayHocParameter, soLuongHVParameter, soTienParameter);
        }
    
        public virtual int CapNhatMonHoc(Nullable<int> maMH, string tenMH, Nullable<int> soGioHoc)
        {
            var maMHParameter = maMH.HasValue ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(int));
    
            var tenMHParameter = tenMH != null ?
                new ObjectParameter("TenMH", tenMH) :
                new ObjectParameter("TenMH", typeof(string));
    
            var soGioHocParameter = soGioHoc.HasValue ?
                new ObjectParameter("SoGioHoc", soGioHoc) :
                new ObjectParameter("SoGioHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatMonHoc", maMHParameter, tenMHParameter, soGioHocParameter);
        }
    
        public virtual int CapNhatNhanVien(Nullable<int> maNV, string tenNV, Nullable<System.DateTime> ngaySinh, string gioiTinh, string cMND, Nullable<int> luong, string mail)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatNhanVien", maNVParameter, tenNVParameter, ngaySinhParameter, gioiTinhParameter, cMNDParameter, luongParameter, mailParameter);
        }
    
        public virtual ObjectResult<KiemTraDangNhap_Result> KiemTraDangNhap(string i_Mail, string i_MatKhau, string i_Quyen, string o_Mail, string o_MatKhau, string o_Quyen)
        {
            var i_MailParameter = i_Mail != null ?
                new ObjectParameter("i_Mail", i_Mail) :
                new ObjectParameter("i_Mail", typeof(string));
    
            var i_MatKhauParameter = i_MatKhau != null ?
                new ObjectParameter("i_MatKhau", i_MatKhau) :
                new ObjectParameter("i_MatKhau", typeof(string));
    
            var i_QuyenParameter = i_Quyen != null ?
                new ObjectParameter("i_Quyen", i_Quyen) :
                new ObjectParameter("i_Quyen", typeof(string));
    
            var o_MailParameter = o_Mail != null ?
                new ObjectParameter("o_Mail", o_Mail) :
                new ObjectParameter("o_Mail", typeof(string));
    
            var o_MatKhauParameter = o_MatKhau != null ?
                new ObjectParameter("o_MatKhau", o_MatKhau) :
                new ObjectParameter("o_MatKhau", typeof(string));
    
            var o_QuyenParameter = o_Quyen != null ?
                new ObjectParameter("o_Quyen", o_Quyen) :
                new ObjectParameter("o_Quyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KiemTraDangNhap_Result>("KiemTraDangNhap", i_MailParameter, i_MatKhauParameter, i_QuyenParameter, o_MailParameter, o_MatKhauParameter, o_QuyenParameter);
        }
    
        public virtual int ThemBienLai(Nullable<int> maHocVien, Nullable<int> maLopHoc, Nullable<int> maKhoaHoc, string hoaDon)
        {
            var maHocVienParameter = maHocVien.HasValue ?
                new ObjectParameter("MaHocVien", maHocVien) :
                new ObjectParameter("MaHocVien", typeof(int));
    
            var maLopHocParameter = maLopHoc.HasValue ?
                new ObjectParameter("MaLopHoc", maLopHoc) :
                new ObjectParameter("MaLopHoc", typeof(int));
    
            var maKhoaHocParameter = maKhoaHoc.HasValue ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(int));
    
            var hoaDonParameter = hoaDon != null ?
                new ObjectParameter("HoaDon", hoaDon) :
                new ObjectParameter("HoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemBienLai", maHocVienParameter, maLopHocParameter, maKhoaHocParameter, hoaDonParameter);
        }
    
        public virtual int ThemDangNhap(string mail, string matKhau, string quyenDangNhap)
        {
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var quyenDangNhapParameter = quyenDangNhap != null ?
                new ObjectParameter("QuyenDangNhap", quyenDangNhap) :
                new ObjectParameter("QuyenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDangNhap", mailParameter, matKhauParameter, quyenDangNhapParameter);
        }
    
        public virtual int ThemGiangVien(Nullable<int> maGV, string tenGV, Nullable<System.DateTime> ngaySinh, Nullable<int> thamNien, string hocVi, Nullable<int> luong, string mail)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var thamNienParameter = thamNien.HasValue ?
                new ObjectParameter("ThamNien", thamNien) :
                new ObjectParameter("ThamNien", typeof(int));
    
            var hocViParameter = hocVi != null ?
                new ObjectParameter("HocVi", hocVi) :
                new ObjectParameter("HocVi", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemGiangVien", maGVParameter, tenGVParameter, ngaySinhParameter, thamNienParameter, hocViParameter, luongParameter, mailParameter);
        }
    
        public virtual int ThemHocVien(Nullable<int> maHV, string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, string soDienThoai)
        {
            var maHVParameter = maHV.HasValue ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemHocVien", maHVParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, soDienThoaiParameter);
        }
    
        public virtual int ThemKetQua(Nullable<int> maHocVien, Nullable<int> maLopHoc, Nullable<int> maKhoaHoc, Nullable<double> diemGiuaKy, Nullable<double> diemCuoiKy, Nullable<double> diemTB)
        {
            var maHocVienParameter = maHocVien.HasValue ?
                new ObjectParameter("MaHocVien", maHocVien) :
                new ObjectParameter("MaHocVien", typeof(int));
    
            var maLopHocParameter = maLopHoc.HasValue ?
                new ObjectParameter("MaLopHoc", maLopHoc) :
                new ObjectParameter("MaLopHoc", typeof(int));
    
            var maKhoaHocParameter = maKhoaHoc.HasValue ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(int));
    
            var diemGiuaKyParameter = diemGiuaKy.HasValue ?
                new ObjectParameter("DiemGiuaKy", diemGiuaKy) :
                new ObjectParameter("DiemGiuaKy", typeof(double));
    
            var diemCuoiKyParameter = diemCuoiKy.HasValue ?
                new ObjectParameter("DiemCuoiKy", diemCuoiKy) :
                new ObjectParameter("DiemCuoiKy", typeof(double));
    
            var diemTBParameter = diemTB.HasValue ?
                new ObjectParameter("DiemTB", diemTB) :
                new ObjectParameter("DiemTB", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemKetQua", maHocVienParameter, maLopHocParameter, maKhoaHocParameter, diemGiuaKyParameter, diemCuoiKyParameter, diemTBParameter);
        }
    
        public virtual int ThemKhoaHoc(Nullable<int> maKH, Nullable<System.DateTime> ngayBatDau, Nullable<int> soTuanHoc, string tinhTrang)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var soTuanHocParameter = soTuanHoc.HasValue ?
                new ObjectParameter("SoTuanHoc", soTuanHoc) :
                new ObjectParameter("SoTuanHoc", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemKhoaHoc", maKHParameter, ngayBatDauParameter, soTuanHocParameter, tinhTrangParameter);
        }
    
        public virtual int ThemLopHoc(Nullable<int> maLH, Nullable<int> khoaHoc, Nullable<int> monHoc, Nullable<int> giangVien, string caHoc, string ngayHoc, string soLuongHV, Nullable<int> soTien)
        {
            var maLHParameter = maLH.HasValue ?
                new ObjectParameter("MaLH", maLH) :
                new ObjectParameter("MaLH", typeof(int));
    
            var khoaHocParameter = khoaHoc.HasValue ?
                new ObjectParameter("KhoaHoc", khoaHoc) :
                new ObjectParameter("KhoaHoc", typeof(int));
    
            var monHocParameter = monHoc.HasValue ?
                new ObjectParameter("MonHoc", monHoc) :
                new ObjectParameter("MonHoc", typeof(int));
    
            var giangVienParameter = giangVien.HasValue ?
                new ObjectParameter("GiangVien", giangVien) :
                new ObjectParameter("GiangVien", typeof(int));
    
            var caHocParameter = caHoc != null ?
                new ObjectParameter("CaHoc", caHoc) :
                new ObjectParameter("CaHoc", typeof(string));
    
            var ngayHocParameter = ngayHoc != null ?
                new ObjectParameter("NgayHoc", ngayHoc) :
                new ObjectParameter("NgayHoc", typeof(string));
    
            var soLuongHVParameter = soLuongHV != null ?
                new ObjectParameter("SoLuongHV", soLuongHV) :
                new ObjectParameter("SoLuongHV", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemLopHoc", maLHParameter, khoaHocParameter, monHocParameter, giangVienParameter, caHocParameter, ngayHocParameter, soLuongHVParameter, soTienParameter);
        }
    
        public virtual int ThemMonHoc(Nullable<int> maMH, string tenMH, Nullable<int> soGioHoc)
        {
            var maMHParameter = maMH.HasValue ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(int));
    
            var tenMHParameter = tenMH != null ?
                new ObjectParameter("TenMH", tenMH) :
                new ObjectParameter("TenMH", typeof(string));
    
            var soGioHocParameter = soGioHoc.HasValue ?
                new ObjectParameter("SoGioHoc", soGioHoc) :
                new ObjectParameter("SoGioHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemMonHoc", maMHParameter, tenMHParameter, soGioHocParameter);
        }
    
        public virtual int ThemNhanVien(Nullable<int> maNV, string tenNV, Nullable<System.DateTime> ngaySinh, string gioiTinh, string cMND, Nullable<int> luong, string mail)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNhanVien", maNVParameter, tenNVParameter, ngaySinhParameter, gioiTinhParameter, cMNDParameter, luongParameter, mailParameter);
        }
    
        public virtual int XoaBienLai(Nullable<int> maHocVien, Nullable<int> maLopHoc, Nullable<int> maKhoaHoc)
        {
            var maHocVienParameter = maHocVien.HasValue ?
                new ObjectParameter("MaHocVien", maHocVien) :
                new ObjectParameter("MaHocVien", typeof(int));
    
            var maLopHocParameter = maLopHoc.HasValue ?
                new ObjectParameter("MaLopHoc", maLopHoc) :
                new ObjectParameter("MaLopHoc", typeof(int));
    
            var maKhoaHocParameter = maKhoaHoc.HasValue ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaBienLai", maHocVienParameter, maLopHocParameter, maKhoaHocParameter);
        }
    
        public virtual int XoaDangNhap(string mail)
        {
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDangNhap", mailParameter);
        }
    
        public virtual int XoaGiangVien(Nullable<int> maGV)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaGiangVien", maGVParameter);
        }
    
        public virtual int XoaHocVien(Nullable<int> maHV)
        {
            var maHVParameter = maHV.HasValue ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaHocVien", maHVParameter);
        }
    
        public virtual int XoaKetQua(Nullable<int> maHocVien, Nullable<int> maLopHoc, Nullable<int> maKhoaHoc)
        {
            var maHocVienParameter = maHocVien.HasValue ?
                new ObjectParameter("MaHocVien", maHocVien) :
                new ObjectParameter("MaHocVien", typeof(int));
    
            var maLopHocParameter = maLopHoc.HasValue ?
                new ObjectParameter("MaLopHoc", maLopHoc) :
                new ObjectParameter("MaLopHoc", typeof(int));
    
            var maKhoaHocParameter = maKhoaHoc.HasValue ?
                new ObjectParameter("MaKhoaHoc", maKhoaHoc) :
                new ObjectParameter("MaKhoaHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaKetQua", maHocVienParameter, maLopHocParameter, maKhoaHocParameter);
        }
    
        public virtual int XoaKhoaHoc(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaKhoaHoc", maKHParameter);
        }
    
        public virtual int XoaLopHoc(Nullable<int> maLH, Nullable<int> khoaHoc)
        {
            var maLHParameter = maLH.HasValue ?
                new ObjectParameter("MaLH", maLH) :
                new ObjectParameter("MaLH", typeof(int));
    
            var khoaHocParameter = khoaHoc.HasValue ?
                new ObjectParameter("KhoaHoc", khoaHoc) :
                new ObjectParameter("KhoaHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaLopHoc", maLHParameter, khoaHocParameter);
        }
    
        public virtual int XoaMonHoc(Nullable<int> maMH)
        {
            var maMHParameter = maMH.HasValue ?
                new ObjectParameter("MaMH", maMH) :
                new ObjectParameter("MaMH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaMonHoc", maMHParameter);
        }
    
        public virtual int XoaNhanVien(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNhanVien", maNVParameter);
        }
    }
}
